version: 0.0
os: linux
files:
  - source: api.tar
    destination: /api

file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"

hooks:
  ApplicationStart:
    - location: script.sh
